FROM python:3.12-slim

WORKDIR /app

# Add project root to PYTHONPATH
ENV PYTHONPATH=/app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest

COPY app/ app/
COPY tests/ tests/

CMD ["pytest", "-v"]
